<a href="https://colab.research.google.com/github/canseel/gelecek-hayalim-wcode/blob/main/week5_1_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Gelecek Hayalim: W-Code 2.0 Veri Bilimi ve Yapay Zeka Atolyesi Homework Week 5-1

Homework 1



> sozluk = {"Kategori": ["Giyim","Giyim", "Ayakkabı","Aksesuar","Ayakkabı","Giyim","Aksesuar","Aksesuar","Ayakkabı","Giyim"],
         "Ürün" : ["Kazak","T-shirt","Sandalet","Küpe","Spor Ayakkabı","Pantolon","Kolye","Yüzük","Çizme","Ceket"],
         "Fiyat" : [300,180,450,50,700,400,150,80,850,900]}



Yukarıdaki sözlüğü bir DataFrme haline getirin

In [ ]:
import pandas as pd

sozluk = {
    "Kategori": ["Giyim","Giyim", "Ayakkabı","Aksesuar","Ayakkabı","Giyim","Aksesuar","Aksesuar","Ayakkabı","Giyim"],
    "Ürün" : ["Kazak","T-shirt","Sandalet","Küpe","Spor Ayakkabı","Pantolon","Kolye","Yüzük","Çizme","Ceket"],
    "Fiyat" : [300,180,450,50,700,400,150,80,850,900]
}

df = pd.DataFrame(sozluk)
print(df)

   Kategori           Ürün  Fiyat
0     Giyim          Kazak    300
1     Giyim        T-shirt    180
2  Ayakkabı       Sandalet    450
3  Aksesuar           Küpe     50
4  Ayakkabı  Spor Ayakkabı    700
5     Giyim       Pantolon    400
6  Aksesuar          Kolye    150
7  Aksesuar          Yüzük     80
8  Ayakkabı          Çizme    850
9     Giyim          Ceket    900

Homework 2

Aşağıdaki işlemleri dataframe üzerinde uygulayalım.



2.indexde bulunan kategoriyi bulalım (Sadece kategori bilgisi)

2.indexde bulunan ürünü bulalım (Sadece ürün bilgisi)

4.indexden 9.indexe kadar olan verileri bulalım (Kategori,ürün,fiyat bilgisi beraber)

1.indexden 6.indexe kadar olan ürünleri bulalım (Sadece ürün bilgisi)

In [ ]:
df.loc[2, "Kategori"] #kategorinin 2. indexi, df.loc[satır, kolon]

'Ayakkabı'

In [ ]:
df.loc[2, "Ürün"] #ürünün 2. indexi

'Sandalet'

In [7]:
df.loc[4:9, ["Kategori", "Ürün", "Fiyat"]]

   Kategori           Ürün  Fiyat
4  Ayakkabı  Spor Ayakkabı    700
5     Giyim       Pantolon    400
6  Aksesuar          Kolye    150
7  Aksesuar          Yüzük     80
8  Ayakkabı          Çizme    850
9     Giyim          Ceket    900

In [8]:
df.loc[1:9, "Ürün"]

1          T-shirt
2         Sandalet
3             Küpe
4    Spor Ayakkabı
5         Pantolon
6            Kolye
7            Yüzük
8            Çizme
9            Ceket
Name: Ürün, dtype: object

Homework 3

Aşağıdaki işlemleri dataframe üzerinde uygulayalım.

Giyim kategorisinde bulunan ürünleri gösterin

Ayakkabı kategorisinde bulunan ürünleri gösterin

Aksesuar kategorisinde bulunan ürünleri gösterin

In [10]:
df[df["Kategori"] == "Giyim"]["Ürün"] #Giyim kategorisindeki ürünler

0       Kazak
1     T-shirt
5    Pantolon
9       Ceket
Name: Ürün, dtype: object

In [11]:
df[df["Kategori"] == "Ayakkabı"]["Ürün"] #Ayakkabı kategorisindeki ürünler

2         Sandalet
4    Spor Ayakkabı
8            Çizme
Name: Ürün, dtype: object

In [12]:
df[df["Kategori"] == "Aksesuar"]["Ürün"] #Aksesuar kategorisindeki ürünler

3     Küpe
6    Kolye
7    Yüzük
Name: Ürün, dtype: object

Homework 4

 Aşağıdaki işlemleri dataframe üzerinde uygulayalım.

Giyim kategorisinde fiyatı 300'den fazla olan ürünleri gösterin

Ayakkabı kategorisinde fiyatı 600'den az olan ürünleri gösterin

Aksesuar kategorisinde fiyatı 100'den fazla olan aksesuarı gösterin

In [13]:
df[(df["Kategori"] == "Giyim") & (df["Fiyat"] > 300)] #Giyim kategosinde fiyatı 300den fazla olan ürünler

  Kategori      Ürün  Fiyat
5    Giyim  Pantolon    400
9    Giyim     Ceket    900

In [14]:
df[(df["Kategori"] == "Ayakkabı") & (df["Fiyat"] < 600)] #Ayakkabı kategosinde fiyatı 600den az olan ürünler

   Kategori      Ürün  Fiyat
2  Ayakkabı  Sandalet    450

In [16]:
df[(df["Kategori"] == "Aksesuar") & (df["Fiyat"] > 100)] #Aksesuar kategorisinde fiyatı 100den fazla olan ürünler

   Kategori   Ürün  Fiyat
6  Aksesuar  Kolye    150